const getters = {
  wareTableData: [
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
    {
      code: '12313',
      name: '猫电费',
      pic: require('../assets/img/touxiang.jpg'),
      store: 12,
      type: '2',
      price: 123123123,
      sex: 0,
      age: '3个月',
      health: 1
    },
  ]
};
export default getters;